### ISSUE TITLE
Partial _person

### ISSUE THREAD

**Issue by alexisben** [noesya/osuny-hugo-template#4]
Dans layouts/partials/persons/person.html, à la ligne : 

```<p>{{- truncate 120 (safeHTML (plainify .Content)) -}}</p>```

Le résultat ne génère pas de saut de ligne ou d'espace entre le titre et le texte.

![image](https://user-images.githubusercontent.com/4630530/161278183-3404abe1-e3ba-4904-b52e-f8403374cdb5.png)

**Comment by alexisben** [comment]
Je n'ai pas trouvé de solution, il faut écrire un filtre ?

**Comment by sebousan** [comment]
@alexisben j'ai fait un partial https://github.com/noesya/osuny-hugo-theme/commit/4633d106eb7e4cf9f4f81033e59217515e77a6e3
